package qupath.ext.omero.annotate.omero;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import qupath.ext.omero.annotate.core.AnnotationConfig;
import qupath.ext.omero.annotate.core.ImageAnnotationRecord;
import qupath.lib.objects.PathObject;
import qupath.lib.roi.interfaces.ROI;

import java.io.IOException;
import java.lang.reflect.Method;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Uploads annotation results to OMERO: label masks, ROIs, and configuration.
 * <p>
 * All OMERO operations use reflection to avoid compile-time dependencies.
 * Methods are no-ops when OMERO is unavailable (local-only mode).
 */
public class OmeroUploader {

    private static final Logger logger = LoggerFactory.getLogger(OmeroUploader.class);

    private static final String CONFIG_NAMESPACE = "openmicroscopy.org/omero/annotate/config";

    private final OmeroConnectionManager connectionManager;
    private final OmeroTableManager tableManager;

    public OmeroUploader(OmeroConnectionManager connectionManager) {
        this.connectionManager = connectionManager;
        this.tableManager = new OmeroTableManager(connectionManager);
    }

    /**
     * Upload a label mask as a FileAnnotation to an OMERO image.
     *
     * @param imageId  OMERO image ID
     * @param maskPath local path to the mask TIFF file
     * @return the FileAnnotation ID, or -1 if upload failed
     */
    public long uploadLabelMask(long imageId, Path maskPath) {
        if (!connectionManager.isConnected()) {
            logger.debug("Not connected to OMERO, skipping mask upload");
            return -1;
        }

        try {
            var gateway = connectionManager.getGateway();
            var ctx = connectionManager.getSecurityContext();

            // Get DataManagerFacility
            Class<?> dmFacilityClass = Class.forName("omero.gateway.facility.DataManagerFacility");
            Method getFacility = gateway.getClass().getMethod("getFacility", Class.class);
            Object dmFacility = getFacility.invoke(gateway, dmFacilityClass);

            // Create FileAnnotationData
            Class<?> fileAnnotationClass = Class.forName("omero.gateway.model.FileAnnotationData");
            Object fileAnnotation = fileAnnotationClass
                    .getDeclaredConstructor(java.io.File.class)
                    .newInstance(maskPath.toFile());

            // Set description
            Method setDescription = fileAnnotation.getClass().getMethod("setDescription", String.class);
            setDescription.invoke(fileAnnotation, "Label mask generated by QuPath OMERO Annotate AI");

            // Attach to image
            Class<?> imageDataClass = Class.forName("omero.gateway.model.ImageData");
            Object imageData = imageDataClass.getDeclaredConstructor().newInstance();
            Method setId = imageData.getClass().getMethod("setId", long.class);
            setId.invoke(imageData, imageId);

            Method attachAnnotation = dmFacility.getClass().getMethod(
                    "attachAnnotation", ctx.getClass(),
                    Class.forName("omero.gateway.model.AnnotationData"),
                    Class.forName("omero.gateway.model.DataObject")
            );
            Object result = attachAnnotation.invoke(dmFacility, ctx, fileAnnotation, imageData);

            Method getId = result.getClass().getMethod("getId");
            long annotationId = (long) getId.invoke(result);

            logger.info("Uploaded label mask to OMERO image {} as FileAnnotation {}", imageId, annotationId);
            return annotationId;

        } catch (Exception e) {
            logger.error("Failed to upload label mask for image {}: {}", imageId, e.getMessage(), e);
            return -1;
        }
    }

    /**
     * Upload QuPath annotations as OMERO ROIs on an image.
     *
     * @param imageId     OMERO image ID
     * @param annotations QuPath PathObjects to convert and upload
     * @return list of created OMERO ROI IDs
     */
    public List<Long> uploadRois(long imageId, List<PathObject> annotations) {
        var roiIds = new ArrayList<Long>();

        if (!connectionManager.isConnected()) {
            logger.debug("Not connected to OMERO, skipping ROI upload");
            return roiIds;
        }

        try {
            var gateway = connectionManager.getGateway();
            var ctx = connectionManager.getSecurityContext();

            // Get ROIFacility
            Class<?> roiFacilityClass = Class.forName("omero.gateway.facility.ROIFacility");
            Method getFacility = gateway.getClass().getMethod("getFacility", Class.class);
            Object roiFacility = getFacility.invoke(gateway, roiFacilityClass);

            for (var annotation : annotations) {
                ROI roi = annotation.getROI();
                if (roi == null) continue;

                try {
                    // Create OMERO ROIData
                    Class<?> roiDataClass = Class.forName("omero.gateway.model.ROIData");
                    Object roiData = roiDataClass.getDeclaredConstructor().newInstance();

                    // Convert QuPath ROI to OMERO shape
                    Object omeroShape = convertToOmeroShape(roi, annotation);
                    if (omeroShape == null) continue;

                    // Add shape to ROI
                    Method addShapeData = roiData.getClass().getMethod(
                            "addShapeData",
                            Class.forName("omero.gateway.model.ShapeData")
                    );
                    addShapeData.invoke(roiData, omeroShape);

                    // Save ROI
                    Method saveROIs = roiFacility.getClass().getMethod(
                            "saveROIs", ctx.getClass(), long.class, java.util.Collection.class
                    );
                    Object savedRois = saveROIs.invoke(roiFacility, ctx, imageId, List.of(roiData));

                    // Extract saved ROI IDs
                    if (savedRois instanceof java.util.Collection<?> collection) {
                        for (var saved : collection) {
                            Method getId = saved.getClass().getMethod("getId");
                            roiIds.add((long) getId.invoke(saved));
                        }
                    }

                } catch (Exception e) {
                    logger.warn("Failed to upload ROI for annotation: {}", e.getMessage());
                }
            }

            logger.info("Uploaded {} ROIs to OMERO image {}", roiIds.size(), imageId);

        } catch (Exception e) {
            logger.error("Failed to upload ROIs for image {}: {}", imageId, e.getMessage(), e);
        }

        return roiIds;
    }

    /**
     * Upload workflow configuration as a YAML FileAnnotation on a dataset.
     *
     * @param datasetId the OMERO dataset ID
     * @param config    the annotation configuration
     * @return the FileAnnotation ID, or -1 if upload failed
     */
    public long uploadConfig(long datasetId, AnnotationConfig config) {
        if (!connectionManager.isConnected()) {
            logger.debug("Not connected to OMERO, skipping config upload");
            return -1;
        }

        try {
            // Save config to temp file
            Path tempFile = Files.createTempFile("annotation_config_", ".yaml");
            config.saveToYaml(tempFile);

            var gateway = connectionManager.getGateway();
            var ctx = connectionManager.getSecurityContext();

            // Get DataManagerFacility
            Class<?> dmFacilityClass = Class.forName("omero.gateway.facility.DataManagerFacility");
            Method getFacility = gateway.getClass().getMethod("getFacility", Class.class);
            Object dmFacility = getFacility.invoke(gateway, dmFacilityClass);

            // Create FileAnnotationData with namespace
            Class<?> fileAnnotationClass = Class.forName("omero.gateway.model.FileAnnotationData");
            Object fileAnnotation = fileAnnotationClass
                    .getDeclaredConstructor(java.io.File.class)
                    .newInstance(tempFile.toFile());
            Method setNamespace = fileAnnotation.getClass().getMethod("setNameSpace", String.class);
            setNamespace.invoke(fileAnnotation, CONFIG_NAMESPACE);
            Method setDescription = fileAnnotation.getClass().getMethod("setDescription", String.class);
            setDescription.invoke(fileAnnotation, "Annotation workflow config (QuPath)");

            // Attach to dataset
            Class<?> datasetDataClass = Class.forName("omero.gateway.model.DatasetData");
            Object datasetData = datasetDataClass.getDeclaredConstructor().newInstance();
            Method setId = datasetData.getClass().getMethod("setId", long.class);
            setId.invoke(datasetData, datasetId);

            Method attachAnnotation = dmFacility.getClass().getMethod(
                    "attachAnnotation", ctx.getClass(),
                    Class.forName("omero.gateway.model.AnnotationData"),
                    Class.forName("omero.gateway.model.DataObject")
            );
            Object result = attachAnnotation.invoke(dmFacility, ctx, fileAnnotation, datasetData);

            // Clean up temp file
            Files.deleteIfExists(tempFile);

            Method getId = result.getClass().getMethod("getId");
            long annotationId = (long) getId.invoke(result);

            logger.info("Uploaded config to OMERO dataset {} as FileAnnotation {}", datasetId, annotationId);
            return annotationId;

        } catch (Exception e) {
            logger.error("Failed to upload config to dataset {}: {}", datasetId, e.getMessage(), e);
            return -1;
        }
    }

    /**
     * Full upload workflow: export results + upload to OMERO + update tracking table.
     *
     * @param datasetId  OMERO dataset ID
     * @param config     annotation configuration
     * @param records    records to upload
     * @param outputDir  local output directory with masks
     * @return true if upload completed successfully
     */
    public boolean uploadAll(long datasetId, AnnotationConfig config,
                             List<ImageAnnotationRecord> records, Path outputDir) {
        if (!connectionManager.isConnected()) {
            logger.warn("Cannot upload: not connected to OMERO");
            return false;
        }

        // Create or update tracking table
        long tableId;
        if (config.getOmero().tableId != null && config.getOmero().tableId > 0) {
            tableId = config.getOmero().tableId;
            tableManager.addRows(tableId, records);
        } else {
            tableId = tableManager.createTable(datasetId, records);
            config.getOmero().tableId = tableId;
        }

        if (tableId < 0) {
            logger.error("Failed to create/update tracking table");
            return false;
        }

        // Upload label masks for each record
        Path maskDir = outputDir.resolve("output");
        for (var record : records) {
            String fileName = String.format("%s_%d_%d.tif",
                    record.getImageName(), record.getChannel(),
                    record.getPatchX()); // Use patchX as index proxy
            Path maskPath = maskDir.resolve(fileName);
            if (Files.exists(maskPath)) {
                long labelId = uploadLabelMask(record.getImageId(), maskPath);
                if (labelId > 0) {
                    record.setLabelId(labelId);
                }
            }
        }

        // Upload config
        uploadConfig(datasetId, config);

        logger.info("Upload complete: {} records to dataset {}", records.size(), datasetId);
        return true;
    }

    public OmeroTableManager getTableManager() {
        return tableManager;
    }

    /**
     * Convert a QuPath ROI to an OMERO ShapeData using reflection.
     */
    private Object convertToOmeroShape(ROI roi, PathObject annotation) throws Exception {
        // Determine shape type based on ROI
        String roiType = roi.getRoiName();
        var geometry = roi.getGeometry();

        // Create PolygonData from coordinates (works for most shapes)
        Class<?> polygonDataClass = Class.forName("omero.gateway.model.PolygonData");

        var coords = geometry.getCoordinates();
        var xCoords = new ArrayList<Double>();
        var yCoords = new ArrayList<Double>();
        for (var coord : coords) {
            xCoords.add(coord.x);
            yCoords.add(coord.y);
        }

        // Create lists of points
        Object polygonData = polygonDataClass.getDeclaredConstructor(
                List.class, List.class
        ).newInstance(xCoords, yCoords);

        // Set Z and T
        Method setZ = polygonData.getClass().getMethod("setZ", int.class);
        Method setT = polygonData.getClass().getMethod("setT", int.class);
        setZ.invoke(polygonData, roi.getZ());
        setT.invoke(polygonData, roi.getT());

        // Set text label if annotation has a class
        if (annotation.getPathClass() != null) {
            Method setText = polygonData.getClass().getMethod("setText", String.class);
            setText.invoke(polygonData, annotation.getPathClass().toString());
        }

        return polygonData;
    }
}
