microsam:
  model_type: "vit_b_lm"  # Default SAM model
  timepoints: [0]
  z_slices: [0]
  three_d: false
  timepoint_mode: "specific"
  z_slice_mode: "specific"

omero:
  container_type: "project"
  container_id: 101
  channel: 3
  source_desc: "Micro-SAM annotation test"

batch_processing:
  batch_size: 0  # 0 = process all images in one batch (default)
  output_folder: "./output"

patches:
  use_patches: true
  patch_size: [256, 256]
  patches_per_image: 1
  random_patches: true

training:
  segment_all: true
  train_n: 3
  validate_n: 3
  trainingset_name: "test_training_data"

workflow:
  resume_from_table: false
  read_only_mode: false
  local_output_dir: "./local_annotations"